postgres

psql postgres

CREATE DATABASE <database name>; --> nextjs_ecommerce
CREATE USER <user name> WITH ENCRYPTED PASSWORD '<user password>'; --> admin; admin
GRANT ALL PRIVILEGES ON DATABASE <database name> TO <user name>; --> products

\q
psql -U <user name> <database name> --> admin

CREATE TABLE products (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(100) NOT NULL,
desc VARCHAR(700) NOT NULL,
price integer NOT NULL,
image VARCHAR(50) NOT NULL);

INSERT INTO products
  (name, description, price, image)
VALUES
('Gravel Bike - Explorer Titanium','The Explorer is our ultimate all-round bike for some serious business!', 4399, 'bike_kevin.jpg'),
('Gravel Bike - Explorer Steel', 'The Explorer is our ultimate all-round bike for some serious business!', 3399, 'bike_kevinsteel.jpg'),
('Allroad Bike - Ultra Titanium','The Ultra is our ultimate endurance machine to eat mile after mile!', 4499, 'bike_ultra.jpg'),
('Tent - 1 Person','This comfortable tent will house one person.', 199, 'tent_1person.jpg'),
('Tent - 2 Persons','This comfortable tent will house two persons.', 299, 'tent_2person.jpg'),
('Tent - 3 Persons','This comfortable tent will house three persons.', 399, 'tent_3person.jpg'),
('Jenkins Handlebar Bag','Bring all your important belongings in this spacious handlebar bag', 149, 'barbag.jpg'),
('Rooter Frame Bag', 'Bring all your important belongings in this spacious frame bag', 179, 'framebag.jpg'),
('Cakadoo Saddle Bag', 'Bring all your important belongings in this spacious saddle bag', 199, 'saddlebag.jpg'),
('Mount Everest - Sleeping Bag Men', 'For those long and cozy nights outdoors, this sleeping bag is the perfect companion.', 279, 'sleepingbag_men.jpg'),
('Mount Everest - Sleeping Bag Women', 'For those long and cozy nights outdoors, this sleeping bag is the perfect companion.', 279, 'sleepingbag_women.jpg'),
('Wilma - Sleeping Mat', 'Small like a bottle of water when packed, this sleeping mat will unfold to a super comfy air bed in just seconds.', 129, 'sleepingmat.jpg'),
('Chamois Creme (500ml)', 'Do you care about your most valuable body part? Then this chamois creme is just the thing for you.', 19, 'butt_creme.jpg'),
('Soto Cooker', 'Fueling up on your adventure is crucial. The multi-cooker will make sure that you can enjoy your Pasta in every corner of the world.', 149, 'cooker.jpg'),
('Park Tool - Patch kit', 'Terrain can be rough on your adventure rig. This patch kit will make sure you can hop back on your bike and continue to enjoy the ride.', 12, 'patchkit.jpg'),
('Park Tool - Bike repair box', 'This bike repair box will contain every tool needed to fix and prepare your adventure rig for the big journey.', 199, 'repairkit.jpg');